# Generated by Django 5.2.8 on 2026-01-12 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم الجزء')),
                ('name_en', models.CharField(max_length=50, verbose_name='Juz Name')),
            ],
        ),
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recitations/', verbose_name='ملف التلاوة')),
                ('recitation_type', models.CharField(choices=[('murattal', 'Murattal'), ('mujawwad', 'Mujawwad')], max_length=10, verbose_name='نوع التلاوة')),
            ],
        ),
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم القارئ')),
                ('name_en', models.CharField(max_length=100, verbose_name='Reciter Name')),
                ('country_ar', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
                ('country_en', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reciters/', verbose_name='صورة القارئ')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم القائمة')),
                ('name_en', models.CharField(max_length=100, verbose_name='Playlist Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('recitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quraan.recitation', verbose_name='التلاوة')),
            ],
            options={
                'verbose_name': 'سجل التشغيل',
                'verbose_name_plural': 'سجل التشغيل',
                'ordering': ['-played_at'],
            },
        ),
        migrations.AddField(
            model_name='recitation',
            name='reciter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quraan.reciter', verbose_name='القارئ'),
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم السورة')),
                ('name_en', models.CharField(max_length=100, verbose_name='Surah Name')),
                ('total_ayahs', models.PositiveSmallIntegerField(verbose_name='عدد الآيات')),
                ('revelation_type', models.CharField(choices=[('M', 'Makki'), ('D', 'Madani')], max_length=1, verbose_name='نوع النزول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='surahs/', verbose_name='صورة السورة')),
                ('juz', models.ManyToManyField(blank=True, to='quraan.juz', verbose_name='الجزء')),
            ],
        ),
        migrations.AddField(
            model_name='recitation',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quraan.surah', verbose_name='السورة'),
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quraan.playlist', verbose_name='القائمة')),
                ('recitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quraan.recitation', verbose_name='التلاوة')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'recitation')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('recitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quraan.recitation', verbose_name='التلاوة')),
            ],
            options={
                'verbose_name': 'المفضلة',
                'verbose_name_plural': 'المفضلة',
                'unique_together': {('user', 'recitation')},
            },
        ),
    ]
