# Generated by Django 6.0 on 2026-01-21 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quraan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='juz',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='juz',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name_en',
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Default Playlist', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='quraan.recitation'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='recitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='quraan.recitation'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quraan.playlist'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='recitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quraan.recitation'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recitations/'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='recitation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='reciter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quraan.reciter'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quraan.surah'),
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='position',
        ),
    ]
