# Generated by Django 6.0 on 2026-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quraan', '0002_alter_favorite_options_alter_playhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='My Playlist', max_length=200),
        ),
    ]
