# Generated by Django 5.2.8 on 2026-02-07 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quraan', '0003_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='playhistory',
            options={'ordering': ['-played_at']},
        ),
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='recitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history_entries', to='quraan.recitation'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='recitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='quraan.recitation'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recitations/', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='recitation_type',
            field=models.CharField(blank=True, choices=[('murattal', 'Murattal'), ('mujawwad', 'Mujawwad'), ('tajweed', 'Tajweed'), ('other', 'Other')], default='murattal', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'recitation')},
        ),
    ]
